from evidence_pipeline.schemas.base import SourceModality
from evidence_pipeline.schemas.audit import AuditEventRecord
from evidence_pipeline.schemas.audio import AudioUtteranceRecord
from evidence_pipeline.schemas.chat import ChatMessageRecord
from evidence_pipeline.schemas.chunks import ChunkRecord
from evidence_pipeline.schemas.claims import NormalizedClaimRecord, RawClaimRecord, ValidatedClaimRecord
from evidence_pipeline.schemas.evidence import EvidenceRecord
from evidence_pipeline.schemas.image import (
    ImageFeatureClusterRecord,
    ImageRecord,
    ImageRegionEmbeddingRecord,
    ImageRegionRecord,
)
from evidence_pipeline.schemas.jobs import JobRecord
from evidence_pipeline.schemas.pdf import PDFBlockRecord
from evidence_pipeline.schemas.review import ReviewDecisionRecord, ReviewQueueRecord
from evidence_pipeline.schemas.reports import (
    ClaimDuplicateGroupRecord,
    ClaimRepairSuggestionRecord,
    GoldEvaluationRecord,
    GraphEdgeRecord,
    ModelRoutingRecord,
    PIIFindingRecord,
    PIIRedactionRecord,
    PrivacyPolicyViolationRecord,
    RetentionPlanRecord,
)
from evidence_pipeline.schemas.sources import SourceRecord
from evidence_pipeline.schemas.spans import SpanRecord
from evidence_pipeline.schemas.validation import ErrorRecord, QuarantineRecord, ValidationRecord

SCHEMA_REGISTRY = {
    "source": SourceRecord,
    "sources": SourceRecord,
    "chat_message": ChatMessageRecord,
    "chat-message": ChatMessageRecord,
    "chat_messages": ChatMessageRecord,
    "pdf_block": PDFBlockRecord,
    "pdf-block": PDFBlockRecord,
    "pdf_blocks": PDFBlockRecord,
    "audio_utterance": AudioUtteranceRecord,
    "audio-utterance": AudioUtteranceRecord,
    "audio_utterances": AudioUtteranceRecord,
    "image": ImageRecord,
    "images": ImageRecord,
    "image_region": ImageRegionRecord,
    "image-region": ImageRegionRecord,
    "image_regions": ImageRegionRecord,
    "image_region_embedding": ImageRegionEmbeddingRecord,
    "image-region-embedding": ImageRegionEmbeddingRecord,
    "image_region_embeddings": ImageRegionEmbeddingRecord,
    "image_feature_cluster": ImageFeatureClusterRecord,
    "image-feature-cluster": ImageFeatureClusterRecord,
    "image_feature_clusters": ImageFeatureClusterRecord,
    "evidence": EvidenceRecord,
    "chunk": ChunkRecord,
    "chunks": ChunkRecord,
    "span": SpanRecord,
    "spans": SpanRecord,
    "claim.raw": RawClaimRecord,
    "raw-claim": RawClaimRecord,
    "claims.raw": RawClaimRecord,
    "claim.validated": ValidatedClaimRecord,
    "validated-claim": ValidatedClaimRecord,
    "claims.validated": ValidatedClaimRecord,
    "claim.normalized": NormalizedClaimRecord,
    "normalized-claim": NormalizedClaimRecord,
    "claims.normalized": NormalizedClaimRecord,
    "job": JobRecord,
    "jobs": JobRecord,
    "review_decision": ReviewDecisionRecord,
    "review-decision": ReviewDecisionRecord,
    "review_decisions": ReviewDecisionRecord,
    "review_queue": ReviewQueueRecord,
    "review-queue": ReviewQueueRecord,
    "audit_event": AuditEventRecord,
    "audit-event": AuditEventRecord,
    "audit_events": AuditEventRecord,
    "validation": ValidationRecord,
    "validations": ValidationRecord,
    "quarantine": QuarantineRecord,
    "graph_edge": GraphEdgeRecord,
    "graph-edge": GraphEdgeRecord,
    "claim_graph": GraphEdgeRecord,
    "claim_duplicate_group": ClaimDuplicateGroupRecord,
    "claim-duplicate-group": ClaimDuplicateGroupRecord,
    "claim_duplicates": ClaimDuplicateGroupRecord,
    "claim_repair": ClaimRepairSuggestionRecord,
    "claim-repair": ClaimRepairSuggestionRecord,
    "claim_repairs": ClaimRepairSuggestionRecord,
    "gold_eval": GoldEvaluationRecord,
    "gold-eval": GoldEvaluationRecord,
    "gold_evaluation": GoldEvaluationRecord,
    "model_routing": ModelRoutingRecord,
    "model-routing": ModelRoutingRecord,
    "privacy_policy_violation": PrivacyPolicyViolationRecord,
    "privacy-policy-violation": PrivacyPolicyViolationRecord,
    "privacy_policy_violations": PrivacyPolicyViolationRecord,
    "retention_plan": RetentionPlanRecord,
    "retention-plan": RetentionPlanRecord,
    "pii_finding": PIIFindingRecord,
    "pii-finding": PIIFindingRecord,
    "pii_findings": PIIFindingRecord,
    "pii_redaction": PIIRedactionRecord,
    "pii-redaction": PIIRedactionRecord,
    "pii_redactions": PIIRedactionRecord,
    "error": ErrorRecord,
    "errors": ErrorRecord,
}

__all__ = [
    "ChunkRecord",
    "ChatMessageRecord",
    "AudioUtteranceRecord",
    "AuditEventRecord",
    "ClaimDuplicateGroupRecord",
    "ClaimRepairSuggestionRecord",
    "ErrorRecord",
    "GoldEvaluationRecord",
    "EvidenceRecord",
    "GraphEdgeRecord",
    "ImageFeatureClusterRecord",
    "ImageRecord",
    "ImageRegionEmbeddingRecord",
    "ImageRegionRecord",
    "JobRecord",
    "NormalizedClaimRecord",
    "ModelRoutingRecord",
    "PDFBlockRecord",
    "PIIFindingRecord",
    "PIIRedactionRecord",
    "QuarantineRecord",
    "RawClaimRecord",
    "PrivacyPolicyViolationRecord",
    "RetentionPlanRecord",
    "ReviewDecisionRecord",
    "ReviewQueueRecord",
    "SCHEMA_REGISTRY",
    "SourceModality",
    "SourceRecord",
    "SpanRecord",
    "ValidatedClaimRecord",
    "ValidationRecord",
]
